### ISSUE TITLE
Converting jpeg to png/tif

### ISSUE THREAD

**Issue by HanxinHua** [Geli25/bme590final#11]
I'm wondering if there is a valid way to convert jpeg type images to png or tiff types? We tried several ways but the result is that we can only see the pictures with several apps but they broke down when we opened them with photoshop.

**Comment by dward2** [comment]
Have you tried the following?
<https://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.save>

**Comment by HanxinHua** [comment]
We used this. This doesn't work with png files using photoshop.

**Comment by dward2** [comment]
When you say "they broke down when we opened them with photoshop," what does that mean?  Did the images open, but were altered?  Were they just unable to open?  What kind of error did you get?  The .png files you create open in some photo apps, just not photoshop?

If you load in a .png file into your python program and convert it to a .jpeg, will that .jpeg file open in photoshop?

**Comment by HanxinHua** [comment]
We could use photos, painting, or any other kinds of image viewer to open and see the photos. But it just doesn't work with photoshop. The error is shown below. And .jpeg works very well. Just .png and .tif will break down.
![image](https://user-images.githubusercontent.com/42785186/49978938-d1ddb280-ff1a-11e8-81bf-fd83ccbbdce6.png)

**Comment by dward2** [comment]
I'm not sure.  I can only speculate that the encoder making the PNG and or TIFF format may not be including some small amount of metadata that Photoshop wants, but the other viewers don't need.  From a practical standpoint (given that you are 24 hrs from a deadline), is there a reason it needs to work in Photoshop?  If you can successfully open them in other programs, I would just go with that for now.

**Comment by dward2** [comment]
Can you point me to the part of your code that outputs the image file to PNG or TIFF format?

**Comment by HanxinHua** [comment]
When we test locally, it works well with photoshop. I think the problem lies in the download part in js. We used Filesaver to do the job. It this the problem?

**Comment by dward2** [comment]
Sorry, I am unfamiliar with Filesaver.  I would contact Suyash for JS related issues.
