### ISSUE TITLE
Verify Server Running

### ISSUE THREAD

**Issue by dward2** [Geli25/bme590final#31]
I am having difficulty independently connecting to your server running on `vcm-7506.vm.duke.edu`.  Would you please verify that it is active.  And is it using port 5000?  I admit it could be a problem on my end, but I just wanted to check to make sure that the VCM didn't automatically shut down this morning.  Did you deactivate the automatic shutdown?  Thanks.

**Comment by TinaHaitongWang** [comment]
Hello Dr. Ward, Sorry about the confusion. I double check the vcm is running. The port for vcm-7506.vm.duke.edu is 5002 (for local), but if you try to connect to it directly, it may be refused. I have to use the proxy that Suyash introduced in the class which has the set port of 443, so I believe if you want to independently connect to the server, you should use port 443. If that still not working, I need to double check which port @Geli25 use then get back to you.

**Comment by dward2** [comment]
I think that port worked.  I still get an error (because I am making a bad request, just to see if I can reach the server), but the error I get indicates the server is running.  So, thanks.

**Comment by TinaHaitongWang** [comment]
Great, no problem.
